import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import Chatbox from "@/components/shared/Chatbox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <section className="z-40">
          <Chatbox />
      </section>
      <section className="z-50 Navbar">
        <Header />
      </section>
      {children}
      <section className="z-10">
          <Footer />
      </section>
      </body>
    </html>
  );
}
